spring:
  profiles:
    active:
      - dog
      - EN
      - prod
yuan:
  username: sampleUsername
  password: samplePassword
  jdbcUrl: sampleJDBCURL

---
spring:
  profiles:
    - prod
yuan:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcUrl: YmlProdJDBCURL